In [ ]:
from pathlib import Path

import numpy as np
import pandas as pd


PROJECT_ROOT = Path.cwd()

if PROJECT_ROOT.name == "answers":
    PROJECT_ROOT = PROJECT_ROOT.parent

DATA_PATH = PROJECT_ROOT / "data" / "scores_raw.csv"
OUTPUT_DIR = PROJECT_ROOT / "outputs"

if not DATA_PATH.is_file():
    raise FileNotFoundError(
        f"Put your existing scores_raw.csv at: {DATA_PATH}"
    )

pd.set_option("display.max_columns", None)
pd.set_option("display.width", 120)

print("NumPy version:", np.__version__)
print("pandas version:", pd.__version__)


## C1 — Series and DataFrame by hand (2 pts)

Build a `Series` of five marks with student names as the index, and print its `.index` and `.values`. Build the same small table as a `DataFrame` twice — once from a dictionary of lists, once from a list of dictionaries — and show the two are equal. Print `.shape`, `.columns`, `.index`.


In [4]:
marks_series = pd.Series(
    [88, 74, 63, 39, 91],
    index=["Aarav", "Bibek", "Chandni", "Deepika", "Esha"],
    name="marks",
)

print(marks_series)
print("\nSeries index:", marks_series.index)
print("Series values:", marks_series.values)


table_from_lists = pd.DataFrame({
    "name": ["Aarav", "Bibek", "Chandni", "Deepika", "Esha"],
    "marks": [88, 74, 63, 39, 91],
})

table_from_records = pd.DataFrame([
    {"name": "Aarav", "marks": 88},
    {"name": "Bibek", "marks": 74},
    {"name": "Chandni", "marks": 63},
    {"name": "Deepika", "marks": 39},
    {"name": "Esha", "marks": 91},
])

Aarav      88
Bibek      74
Chandni    63
Deepika    39
Esha       91
Name: marks, dtype: int64

Series index: Index(['Aarav', 'Bibek', 'Chandni', 'Deepika', 'Esha'], dtype='str')
Series values: [88 74 63 39 91]


In [5]:
print("\nFrom a dictionary of lists:\n", table_from_lists)
print("\nFrom a list of dictionaries:\n", table_from_records)
print("\nEqual:", table_from_lists.equals(table_from_records))


From a dictionary of lists:
       name  marks
0    Aarav     88
1    Bibek     74
2  Chandni     63
3  Deepika     39
4     Esha     91

From a list of dictionaries:
       name  marks
0    Aarav     88
1    Bibek     74
2  Chandni     63
3  Deepika     39
4     Esha     91

Equal: True


In [6]:
print("\nDictionary-of-lists shape:", table_from_lists.shape)
print("Columns:", table_from_lists.columns)
print("Index:", table_from_lists.index)


Dictionary-of-lists shape: (5, 2)
Columns: Index(['name', 'marks'], dtype='str')
Index: RangeIndex(start=0, stop=5, step=1)


In [7]:
print("\nList-of-dictionaries shape:", table_from_records.shape)
print("Columns:", table_from_records.columns)
print("Index:", table_from_records.index)



List-of-dictionaries shape: (5, 2)
Columns: Index(['name', 'marks'], dtype='str')
Index: RangeIndex(start=0, stop=5, step=1)


## C2 — Load and inspect (3 pts)

Read `scores_raw.csv`. Print `head()`, `tail(3)`, `shape`, `info()`, `describe()`, and `describe(include="object")`. Then write two to three sentences naming three specific problems visible in that output, each backed by a number or a value from it.


In [8]:
df = pd.read_csv(DATA_PATH)
raw_df = df.copy(deep=True)

In [9]:
print("First five rows:\n", df.head())
print("\nLast three rows:\n", df.tail(3))
print("\nShape:", df.shape)

First five rows:
    student_id             name          city           subject  marks  attendance_percent   exam_date
0        1014     Nisha Gurung       POKHARA         Databases   29.0                81.4  2026-02-22
1        1035  Ojaswi Adhikari      Birgunj         Statistics   52.0                80.4  2026-01-17
2        1036    Prakash Karki        DHARAN         Databases   71.0                89.8  2026-02-07
3        1019    Tara Shrestha    Kathmandu   Machine Learning   76.0                81.4  2026-03-09
4        1001   Aarav Shrestha     kathmandu         Databases   93.0                92.2  2026-01-29

Last three rows:
      student_id           name           city           subject  marks  attendance_percent   exam_date
123        1016    Prakash Rai       LALITPUR        Statistics   90.0                64.0  2026-01-06
124        1037  Rita Shrestha      kathmandu  Machine Learning   79.0                61.7  2026-01-28
125        1015   Ojaswi Thapa    Biratnag

In [10]:
print("\nColumn information:")
df.info()


Column information:
<class 'pandas.DataFrame'>
RangeIndex: 126 entries, 0 to 125
Data columns (total 7 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   student_id          126 non-null    int64  
 1   name                126 non-null    str    
 2   city                126 non-null    str    
 3   subject             126 non-null    str    
 4   marks               122 non-null    float64
 5   attendance_percent  116 non-null    float64
 6   exam_date           126 non-null    str    
dtypes: float64(2), int64(1), str(4)
memory usage: 7.0 KB


In [13]:
print("\nNumeric description:\n", df.describe())


Numeric description:
         student_id       marks  attendance_percent
count   126.000000  122.000000          116.000000
mean   1020.460317   60.557377           74.413793
std      11.597690   23.807440           12.514033
min    1001.000000   28.000000           52.500000
25%    1010.250000   42.250000           63.125000
50%    1020.500000   54.000000           73.300000
75%    1030.750000   79.750000           84.000000
max    1040.000000  150.000000           98.600000


In [12]:
print("\nObject description:\n", df.describe(include="object"))


Object description:
                    name        city     subject   exam_date
count               126         126         126         126
unique               40          24           5          66
top     Ojaswi Adhikari  Biratnagar  Statistics  2026-01-29
freq                  4          10          27           4


C:\Users\Lenovo\AppData\Local\Temp\ipykernel_27440\2718704966.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  print("\nObject description:\n", df.describe(include="object"))


In [ ]:
# The ouput has following issues:
# 1. The dataset shows missing values in the marks column. 122 non-null values out of 126 rows (4 missing values).
# 2. Similarly, attendence_percent has 116 non-null values out of 126 rows (10 missing values).
# 3. Potential data quality issues in the marks column as maximum value seems 150.
# 4. City column has inconsistent values like "Kathmandu", "kathmandu", "POKHARA" etc which should be cleaned and standardized.    
# 5. Marks above 100 could be a data entry error. 

## C3 — Selecting rows and columns (3 pts)

Print `df["marks"]` and `df[["marks"]]` with `type()` of each, and say in a comment what the difference is. Then show `df.loc[0:4, ["name", "subject", "marks"]]` and `df.iloc[0:5, 1:4]`, print how many rows each returned, and explain in a comment why the two slices treat their end point differently.


In [14]:
print(df["marks"])
print("Type:", type(df["marks"]))

print("\n", df[["marks"]])
print("Type:", type(df[["marks"]]))

# One column name returns a one-dimensional Series.
# A list of column names returns a two-dimensional DataFrame,
# even when the list contains only one name.

0      29.0
1      52.0
2      71.0
3      76.0
4      93.0
       ... 
121    90.0
122    65.0
123    90.0
124    79.0
125    70.0
Name: marks, Length: 126, dtype: float64
Type: <class 'pandas.Series'>

      marks
0     29.0
1     52.0
2     71.0
3     76.0
4     93.0
..     ...
121   90.0
122   65.0
123   90.0
124   79.0
125   70.0

[126 rows x 1 columns]
Type: <class 'pandas.DataFrame'>


In [15]:
selected_loc = df.loc[0:4, ["name", "subject", "marks"]]
selected_iloc = df.iloc[0:5, 1:4]

print("\nloc selection:\n", selected_loc)
print("Rows returned:", len(selected_loc))

print("\niloc selection:\n", selected_iloc)
print("Rows returned:", len(selected_iloc))

# loc slices by index labels and includes the ending label, 4.
# iloc slices by position and excludes the ending position, 5,
# following normal Python slicing. Both return five rows here
# because the original index is the consecutive labels 0, 1, 2, ... .



loc selection:
               name           subject  marks
0     Nisha Gurung         Databases   29.0
1  Ojaswi Adhikari        Statistics   52.0
2    Prakash Karki         Databases   71.0
3    Tara Shrestha  Machine Learning   76.0
4   Aarav Shrestha         Databases   93.0
Rows returned: 5

iloc selection:
               name          city           subject
0     Nisha Gurung       POKHARA         Databases
1  Ojaswi Adhikari      Birgunj         Statistics
2    Prakash Karki        DHARAN         Databases
3    Tara Shrestha    Kathmandu   Machine Learning
4   Aarav Shrestha     kathmandu         Databases
Rows returned: 5


## C4 — Boolean filtering (3 pts)

(a) Rows with `marks > 80` and subject `"Python Programming"`. (b) Rows from Kathmandu or Pokhara — note that this under-counts until you clean the city column in C5, and say so. (c) The same filter as (a) written with `.query()`, proved identical with `.equals()`. In a comment, explain why `and` / `or` fail inside a bracket filter but are required inside `query()`.


In [21]:
high_python = df.loc[
    (df["marks"] > 80) & (df["subject"] == "Python Programming")
]

print("(a) Python Programming marks above 80:\n", high_python)


city_filter_before = df.loc[df["city"].isin(["Kathmandu", "Pokhara"])]
city_count_before = len(city_filter_before)

print("\n(b) Kathmandu or Pokhara before cleaning:\n", city_filter_before)
print("Rows before cleaning:", city_count_before)

# This under-counts: exact matching misses other capitalisation
# and leading or trailing spaces. C5 will count the same cities again.

(a) Python Programming marks above 80:
      student_id            name        city             subject  marks  attendance_percent   exam_date
5          1009     Ishan Thapa  Biratnagar  Python Programming   98.0                61.2  2026-02-23
73         1006      Faiz Karki      Dharan  Python Programming   81.0                98.5  2026-01-05
117        1011  Kiran Adhikari     Birgunj  Python Programming   89.0                78.3  2026-03-24

(b) Kathmandu or Pokhara before cleaning:
      student_id             name       city             subject  marks  attendance_percent   exam_date
0          1014     Nisha Gurung    Pokhara           Databases   29.0                81.4  2026-02-22
3          1019    Tara Shrestha  Kathmandu    Machine Learning   76.0                81.4  2026-03-09
4          1001   Aarav Shrestha  Kathmandu           Databases   93.0                92.2  2026-01-29
7          1026      Faiz Gurung    Pokhara           Databases   46.0                97.5  

In [22]:
high_python_query = df.query(
    'marks > 80 and subject == "Python Programming"'
)

print("\n(c) query result:\n", high_python_query)
print("Identical results:", high_python.equals(high_python_query))
assert high_python.equals(high_python_query)

# In ordinary Python, and/or ask for one truth value for a whole
# Series. That is ambiguous, so bracket filters need elementwise
# & / |, with each comparison in parentheses.


(c) query result:
      student_id            name        city             subject  marks  attendance_percent   exam_date
5          1009     Ishan Thapa  Biratnagar  Python Programming   98.0                61.2  2026-02-23
73         1006      Faiz Karki      Dharan  Python Programming   81.0                98.5  2026-01-05
117        1011  Kiran Adhikari     Birgunj  Python Programming   89.0                78.3  2026-03-24
Identical results: True


## C5 — Cleaning inconsistent text (3 pts)

Print `df["city"].nunique()` and `value_counts()` before cleaning. Normalise the column with string methods (strip whitespace, fix capitalisation), then print both again. Checkpoint: 24 distinct spellings before, 6 after. Re-run your C4(b) filter and report how many rows you were losing.


In [23]:
print("Distinct city spellings before:", df["city"].nunique())
print(df["city"].value_counts())

df["city"] = df["city"].str.strip().str.title()

print("\nDistinct cities after:", df["city"].nunique())
print(df["city"].value_counts())


city_filter_after = df.loc[df["city"].isin(["Kathmandu", "Pokhara"])]
city_count_after = len(city_filter_after)

print("\nKathmandu or Pokhara after cleaning:\n", city_filter_after)
print("Rows before cleaning:", city_count_before)
print("Rows after cleaning:", city_count_after)
print("Rows previously lost:", city_count_after - city_count_before)

Distinct city spellings before: 6
city
Kathmandu     23
Pokhara       22
Biratnagar    22
Lalitpur      22
Birgunj       19
Dharan        18
Name: count, dtype: int64

Distinct cities after: 6
city
Kathmandu     23
Pokhara       22
Biratnagar    22
Lalitpur      22
Birgunj       19
Dharan        18
Name: count, dtype: int64

Kathmandu or Pokhara after cleaning:
      student_id             name       city             subject  marks  attendance_percent   exam_date
0          1014     Nisha Gurung    Pokhara           Databases   29.0                81.4  2026-02-22
3          1019    Tara Shrestha  Kathmandu    Machine Learning   76.0                81.4  2026-03-09
4          1001   Aarav Shrestha  Kathmandu           Databases   93.0                92.2  2026-01-29
7          1026      Faiz Gurung    Pokhara           Databases   46.0                97.5  2026-03-13
11         1038     Sujan Gurung    Pokhara      Linear Algebra   37.0                70.3  2026-03-09
12         1031  

## C6 — Missing values (3 pts)

Print `isna().sum()` per column. Fill missing `attendance_percent` with the column mean; drop the rows with missing `marks`. Print the row count before and after each step. Then, in two sentences, argue whether mean-filling attendance was a defensible choice here.


In [ ]:
print("Missing values per column:\n", df.isna().sum())

print("\nRows before filling attendance:", len(df))
attendance_mean = df["attendance_percent"].mean()
df["attendance_percent"] = df["attendance_percent"].fillna(attendance_mean)
print("Attendance mean used:", attendance_mean)
print("Rows after filling attendance:", len(df))

print("\nRows before dropping missing marks:", len(df))
df = df.dropna(subset=["marks"]).copy()
print("Rows after dropping missing marks:", len(df))

print("\nMissing values after these steps:\n", df.isna().sum())

# Mean filling is acceptable here because the missing attendance values are random and not so many, 
# hence the average attendance is a reasonable estimate. 
# It is used for simplicity, not precisely because the whole dataset follows a perfect normal distribution.

Missing values per column:
 student_id             0
name                   0
city                   0
subject                0
marks                  4
attendance_percent    10
exam_date              0
dtype: int64

Rows before filling attendance: 126
Attendance mean used: 74.41379310344827
Rows after filling attendance: 126

Rows before dropping missing marks: 126
Rows after dropping missing marks: 122

Missing values after these steps:
 student_id            0
name                  0
city                  0
subject               0
marks                 0
attendance_percent    0
exam_date             0
dtype: int64


## C7 — Duplicates (3 pts)

Using `duplicated()`, print how many fully duplicated rows exist and show a few. Drop them keeping the first occurrence, and print the shape before and after. Checkpoint: 6 duplicates, 126 → 120 rows. Separately, report duplicates on the subset `["student_id", "subject"]`, and explain in a comment why that subset is the one that actually matters here.


In [ ]:
print("Raw-file exact duplicates:", raw_df.duplicated().sum())
print("Raw shape before:", raw_df.shape)
print("Raw shape after dropping duplicates:", raw_df.drop_duplicates().shape)


print("\nWorking-data exact duplicates:", df.duplicated().sum())
print("Examples:\n", df.loc[df.duplicated()].head())

print(
    "\nRepeated student-subject pairs before removal:",
    df.duplicated(subset=["student_id", "subject"]).sum(),
)

print("\nWorking shape before:", df.shape)
df = df.drop_duplicates(keep="first").copy()
print("Working shape after:", df.shape)

pair_duplicates = df.duplicated(subset=["student_id", "subject"])
print("\nRepeated student-subject pairs after removal:", pair_duplicates.sum())
print(df.loc[pair_duplicates])

# The dataset has one record for each student in each subject.
# Student names can be the same, so student_id and subject are used to identify records.
# Duplicate student-subject records may need checking because they could represent errors.

Raw-file exact duplicates: 6
Raw shape before: (126, 7)
Raw shape after dropping duplicates: (120, 7)

Working-data exact duplicates: 0
Examples:
 Empty DataFrame
Columns: [student_id, name, city, subject, marks, attendance_percent, exam_date]
Index: []

Repeated student-subject pairs before removal: 0

Working shape before: (116, 7)
Working shape after: (116, 7)

Repeated student-subject pairs after removal: 0
Empty DataFrame
Columns: [student_id, name, city, subject, marks, attendance_percent, exam_date]
Index: []


## C8 — Dates (3 pts)

Print `exam_date`'s dtype, convert it with `pd.to_datetime()`, and print the dtype again. Add `exam_month` and `exam_weekday` columns using the `.dt` accessor, then filter to exams held after `2026-02-15` and print how many there are.


In [27]:
print("exam_date dtype before:", df["exam_date"].dtype)
df["exam_date"] = pd.to_datetime(df["exam_date"], format="%Y-%m-%d")
print("exam_date dtype after:", df["exam_date"].dtype)

# A year-month Period stays unambiguous if future data spans years.
df["exam_month"] = df["exam_date"].dt.to_period("M")
df["exam_weekday"] = df["exam_date"].dt.day_name()

print("\nDate-derived columns:\n", df[["exam_date", "exam_month", "exam_weekday"]].head())

after_cutoff = df.loc[df["exam_date"] > pd.Timestamp("2026-02-15")]
print("\nExams after 2026-02-15:", len(after_cutoff))

# Strictly after excludes exams on February 15 itself.

exam_date dtype before: str
exam_date dtype after: datetime64[us]

Date-derived columns:
    exam_date exam_month exam_weekday
0 2026-02-22    2026-02       Sunday
1 2026-01-17    2026-01     Saturday
2 2026-02-07    2026-02     Saturday
3 2026-03-09    2026-03       Monday
4 2026-01-29    2026-01     Thursday

Exams after 2026-02-15: 59


## C9 — Sorting and renaming (3 pts)

Sort by `subject` (A–Z) and, within each subject, `marks` (high to low); show the top rows. Rename `attendance_percent` to `attendance` without modifying the original DataFrame, and prove the original is unchanged by printing both `.columns`. Then restore the original row order with `sort_index()`.


In [28]:
sorted_df = df.sort_values(
    by=["subject", "marks"],
    ascending=[True, False],
)

print("Sorted rows:\n", sorted_df.head(10))

renamed_df = sorted_df.rename(columns={"attendance_percent": "attendance"})

print("\nOriginal columns:", df.columns)
print("Renamed columns:", renamed_df.columns)
print("Sorted source columns:", sorted_df.columns)

assert "attendance_percent" in df.columns
assert "attendance" not in df.columns

restored_df = sorted_df.sort_index()
print("\nOriginal row order restored:\n", restored_df.head())
print("Restored data equals original:", restored_df.equals(df))

# The original CSV row labels were kept during cleaning, so sorting
# the index restores the original relative order of surviving rows.

Sorted rows:
      student_id            name        city    subject  marks  attendance_percent  exam_date exam_month exam_weekday
42         1027      Gita Thapa  Biratnagar  Databases   96.0           73.600000 2026-02-25    2026-02    Wednesday
48         1012     Laxmi Karki      Dharan  Databases   94.0           79.500000 2026-01-22    2026-01     Thursday
4          1001  Aarav Shrestha   Kathmandu  Databases   93.0           92.200000 2026-01-29    2026-01     Thursday
100        1022       Bibek Rai    Lalitpur  Databases   92.0           89.400000 2026-02-17    2026-02      Tuesday
21         1015    Ojaswi Thapa  Biratnagar  Databases   87.0           91.400000 2026-01-15    2026-01     Thursday
2          1036   Prakash Karki      Dharan  Databases   71.0           89.800000 2026-02-07    2026-02     Saturday
44         1037   Rita Shrestha   Kathmandu  Databases   71.0           66.200000 2026-01-17    2026-01     Saturday
122        1025   Esha Shrestha   Kathmandu  Datab

## C10 — Derived columns (3 pts)

Add `passed` (`marks >= 40`), and `grade` using nested `np.where`: 85+ → A, 70–84 → B, 40–69 → C, below 40 → F. Print the overall pass rate as a percentage by taking the mean of `passed` cast to `int`, and print `grade.value_counts()`. Deal with the impossible marks values you found in C2, and say in a comment what you did with them and why.

In [29]:
invalid_marks = ~df["marks"].between(0, 100)

print("Impossible marks:\n", df.loc[invalid_marks, ["student_id", "subject", "marks"]])
print("Rows before removing impossible marks:", len(df))

# Assume marks are out of 100. Remove values outside 0–100 before
# assigning grades or calculating summaries. We cannot infer the
# true values, and capping 150 at 100 would invent a perfect score.
# Keep raw_df unchanged so the removed records can still be audited.
df = df.loc[~invalid_marks].copy()

print("Invalid rows removed:", invalid_marks.sum())
print("Rows after removal:", len(df))


df["passed"] = df["marks"] >= 40
df["grade"] = np.where(
    df["marks"] >= 85,
    "A",
    np.where(
        df["marks"] >= 70,
        "B",
        np.where(df["marks"] >= 40, "C", "F"),
    ),
)

pass_rate = df["passed"].astype(int).mean() * 100

print("\nOverall pass rate: {:.2f}%".format(pass_rate))
print("\nGrade counts:\n", df["grade"].value_counts())
print("\nExample derived columns:\n", df[["marks", "passed", "grade"]].head())

# This is the pass rate across retained student-subject results,
# not the proportion of distinct students who passed every subject.


Impossible marks:
     student_id           subject  marks
49        1032  Machine Learning  150.0
51        1039    Linear Algebra  150.0
Rows before removing impossible marks: 116
Invalid rows removed: 2
Rows after removal: 114

Overall pass rate: 78.95%

Grade counts:
 grade
C    53
F    24
A    21
B    16
Name: count, dtype: int64

Example derived columns:
    marks  passed grade
0   29.0   False     F
1   52.0    True     C
2   71.0    True     B
3   76.0    True     B
4   93.0    True     A


## C11 — Types and memory (3 pts)

Convert `subject` and `city` to the `category` dtype. Print `memory_usage(deep=True)` for those two columns before and after, in bytes, and the percentage saved. In a comment, explain what makes `category` cheaper, and when it would not help.


In [30]:
category_columns = ["subject", "city"]

# Exclude the unchanged row index to measure only these columns.
memory_before = df[category_columns].memory_usage(index=False, deep=True)

df["subject"] = df["subject"].astype("category")
df["city"] = df["city"].astype("category")

memory_after = df[category_columns].memory_usage(index=False, deep=True)
percent_saved = (memory_before - memory_after) / memory_before * 100

print("Memory before (bytes):\n", memory_before)
print("\nMemory after (bytes):\n", memory_after)
print("\nPercentage saved per column:\n", percent_saved.round(2))

total_saved = (1 - memory_after.sum() / memory_before.sum()) * 100
print("\nTotal percentage saved: {:.2f}%".format(total_saved))
print("\nNew dtypes:\n", df[category_columns].dtypes)

# A category stores each distinct label once plus small integer codes
# for the rows. This helps because many rows repeat the same few cities
# and subjects. With almost all unique labels, the category lookup and
# codes can cost as much as, or more than, the original column.
# Exact byte counts depend on pandas and the Python environment.

Memory before (bytes):
 subject    7101
city       6487
dtype: int64

Memory after (bytes):
 subject    426
city       455
dtype: int64

Percentage saved per column:
 subject    94.00
city       92.99
dtype: float64

Total percentage saved: 93.52%

New dtypes:
 subject    category
city       category
dtype: object


## C12 — Aggregation and a summary table (3 pts)

On the cleaned data, produce: (a) mean, max and count of `marks` per subject using `groupby().agg()`; (b) mean `marks` by `city` and `subject`; (c) a `pivot_table` of mean marks with cities as rows and subjects as columns; (d) mean marks per `exam_month`, sorted chronologically. Export (a) to `outputs/summary.csv`, and state in one sentence what the month trend shows.


In [31]:
subject_summary = (
    df.groupby("subject", observed=True)["marks"]
    .agg(["mean", "max", "count"])
    .sort_index()
)

print("(a) Marks per subject:\n", subject_summary)


city_subject_mean = (
    df.groupby(["city", "subject"], observed=True)["marks"]
    .mean()
    .sort_index()
)

print("\n(b) Mean marks by city and subject:\n", city_subject_mean)


city_subject_pivot = df.pivot_table(
    index="city",
    columns="subject",
    values="marks",
    aggfunc="mean",
    observed=True,
).sort_index().sort_index(axis=1)

print("\n(c) Mean marks pivot table:\n", city_subject_pivot)


monthly_mean = df.groupby("exam_month")["marks"].mean().sort_index()
print("\n(d) Mean marks per exam month:\n", monthly_mean)

OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
subject_summary.to_csv(OUTPUT_DIR / "summary.csv", index_label="subject")
print("\nExported: outputs/summary.csv")


(a) Marks per subject:
                          mean   max  count
subject                                   
Databases           57.000000  96.0     23
Linear Algebra      51.166667  93.0     24
Machine Learning    59.809524  91.0     21
Python Programming  58.454545  98.0     22
Statistics          67.166667  95.0     24

(b) Mean marks by city and subject:
 city        subject           
Biratnagar  Databases             80.666667
            Linear Algebra        61.666667
            Machine Learning      65.600000
            Python Programming    52.166667
            Statistics            67.666667
Birgunj     Databases             53.000000
            Linear Algebra        59.800000
            Machine Learning      60.333333
            Python Programming    70.666667
            Statistics            60.000000
Dharan      Databases             63.200000
            Linear Algebra        47.666667
            Machine Learning      71.333333
            Python Programming    

## +5 — A reporting pipeline.

Wrap Part C into three functions — `load(path)`, `clean(df)`, `summarise(df)` — so that `summarise(clean(load("data/scores_raw.csv")))` reproduces your C12(a) table from the raw file in one line. It must run top to bottom with no manual steps.


In [32]:
def load(path):
    """Read the CSV; resolve relative paths from the project folder."""
    path = Path(path)

    if not path.is_absolute():
        path = PROJECT_ROOT / path

    return pd.read_csv(path)


def clean(df):
    """Repeat the C5–C11 cleaning choices without changing the input."""
    result = df.copy(deep=True)

    result["city"] = result["city"].str.strip().str.title()

    # Match C6 exactly: compute the mean before dropping any rows.
    attendance_mean = result["attendance_percent"].mean()
    result["attendance_percent"] = result["attendance_percent"].fillna(
        attendance_mean
    )

    result = result.dropna(subset=["marks"]).copy()
    result = result.drop_duplicates(keep="first").copy()

    result["exam_date"] = pd.to_datetime(
        result["exam_date"], format="%Y-%m-%d"
    )
    result["exam_month"] = result["exam_date"].dt.to_period("M")
    result["exam_weekday"] = result["exam_date"].dt.day_name()

    result = result.loc[result["marks"].between(0, 100)].copy()

    result["passed"] = result["marks"] >= 40
    result["grade"] = np.where(
        result["marks"] >= 85,
        "A",
        np.where(
            result["marks"] >= 70,
            "B",
            np.where(result["marks"] >= 40, "C", "F"),
        ),
    )

    result["subject"] = result["subject"].astype("category")
    result["city"] = result["city"].astype("category")

    return result.sort_index()


def summarise(df):
    """Return the C12(a) table in a fixed subject order."""
    return (
        df.groupby("subject", observed=True)["marks"]
        .agg(["mean", "max", "count"])
        .sort_index()
    )


pipeline_summary = summarise(clean(load("data/scores_raw.csv")))

print(pipeline_summary)
print("\nEquals C12(a):", pipeline_summary.equals(subject_summary))

pd.testing.assert_frame_equal(pipeline_summary, subject_summary)
pd.testing.assert_frame_equal(clean(raw_df), df)

print("Pipeline summary and cleaned data both match the earlier answers.")


                         mean   max  count
subject                                   
Databases           57.000000  96.0     23
Linear Algebra      51.166667  93.0     24
Machine Learning    59.809524  91.0     21
Python Programming  58.454545  98.0     22
Statistics          67.166667  95.0     24

Equals C12(a): True
Pipeline summary and cleaned data both match the earlier answers.


## +3 — Where your cleaning could mislead.

150–250 words in `answers/03_pandas.ipynb`: pick two cleaning decisions you made (mean-filling attendance, dropping missing marks, deleting duplicates, whatever you did with the impossible marks) and explain, concretely, how each one could bend the conclusions in your C12 summary.


1. Dropping rows with missing marks: We have dropped 4 marks whose scores were unavailable, however, if the real marks for those rows were very low, the true mean and the mean we got from removing them would be different. We'd get a picture of students doing well even when reality might be different.

2. Removing impossible marks: 150 would raise the mean significantly hence they were removed. However, if the marks for those two records were supposed to be 100 or a 0. The mean would lean to one direction compared to other. Our activity introduces bias to one direction because we chose to remove those values. 